FROM python:3.14.4-slim

WORKDIR /app

COPY fraud-detection/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY fraud-detection/app ./app

EXPOSE 8000

CMD ["sh", "-c", "uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8000}"]