FROM python:3.14.4-slim

WORKDIR /app

COPY fraud-detection/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY fraud-detection/app ./app

EXPOSE 8000

CMD ["fastapi", "run", "app/main.py", "--port", "8000"]